# Generated by Django 4.0.6 on 2022-08-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_message_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_arrival_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
