# Generated by Django 4.0.6 on 2022-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat",
            "0004_rename_is_private_room_is_private_group_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="room",
            name="to_user",
        ),
        migrations.AddField(
            model_name="room_users",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
