# Generated by Django 4.0.6 on 2022-08-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat",
            "0005_remove_room_from_user_remove_room_to_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="hi",
        ),
    ]
