# Generated by Django 4.0.6 on 2022-08-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_remove_room_hi"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.room_users",
            ),
        ),
    ]
