# Generated by Django 4.0.6 on 2022-08-17 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_message_room_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="room_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.room_users",
            ),
        ),
    ]
