# Generated by Django 4.0.6 on 2022-08-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_message_room_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="room_user",
        ),
    ]
