# Generated by Django 4.0.6 on 2022-08-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_room_users_join_request_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='number_of_views',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
