# Generated by Django 4.0.6 on 2022-08-18 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_message_number_of_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='number_of_views',
        ),
        migrations.CreateModel(
            name='SeenMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_inroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
                ('users_in_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room_users')),
            ],
        ),
    ]
