# Generated by Django 4.0.6 on 2022-08-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_rename_message_inroom_seenmessages_message_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seenmessages',
            name='message_in_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
    ]
