# Generated by Django 4.0.6 on 2022-08-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_seenmessages_message_in_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seenmessages',
            name='message_in_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
        migrations.AlterField(
            model_name='seenmessages',
            name='message_seen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
        migrations.AlterField(
            model_name='seenmessages',
            name='users_in_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room_users'),
        ),
    ]
